name: Criar Pod Nginx

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Instalar oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
    
      - name: Criar Pod nginx
        run: |
          oc project openshift-operators
          oc run nginx-test --image=nginx --restart=Never --port=80

      - name: Verificar Pod
        run: oc get pods
