name: Deploy Nginx no OpenShift

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar e preparar oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc

      - name: Validar acesso ao cluster
        run: |
          ./oc whoami
          ./oc project openshift-operators

      - name: Criar Pod nginx
        run: |
          ./oc run nginx-test \
            --image=nginx \
            --restart=Never \
            --port=80 || true

      - name: Verificar Pods
        run: |
          ./oc get pods -n openshift-operators

      - name: Descrever Pod nginx
        run: |
          ./oc describe pod nginx-test -n openshift-operators || true
