name: Deploy Nginx no OpenShift

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
    
      - name: Baixar e preparar oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc

      - name: Validar acesso ao cluster
        run: |
          ./oc whoami
          ./oc project openshift-operators

      - name: Deploy nginx
        run: |
          ./oc apply -f k8s/deploy.yaml

      - name: Verificar Pods
        run: |
          ./oc get pods -n openshift-operators

      - name: Descrever Pod nginx
        run: |
          ./oc describe pod nginx-test -n openshift-operators || true
